# permissions for end users to view gcrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcrd-viewer-role
rules:
- apiGroups:
  - app.gcrd.jerry153fish.com
  resources:
  - gcrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.gcrd.jerry153fish.com
  resources:
  - gcrds/status
  verbs:
  - get
