
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.gcrd.jerry153fish.com
  resources:
  - gcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.gcrd.jerry153fish.com
  resources:
  - gcrds/finalizers
  verbs:
  - update
- apiGroups:
  - app.gcrd.jerry153fish.com
  resources:
  - gcrds/status
  verbs:
  - get
  - patch
  - update
